---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: home-assistant
  commonMetadata:
    labels:
      app.kubernetes.io/name: home-assistant
  dependsOn:
    - name: openebs-lvm
    - name: mosquitto
    - name: cert-manager-issuers
  path: ./kubernetes/apps/home-assistant/home-assistant
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  dependsOn:
    - name: openebs-lvm
  targetNamespace: home-assistant
  commonMetadata:
    labels:
      app.kubernetes.io/name: mosquitto
  path: ./kubernetes/apps/home-assistant/mosquitto
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: home-assistant
  commonMetadata:
    labels:
      app.kubernetes.io/name: zigbee2mqtt
  dependsOn:
    - name: openebs-lvm
    - name: mosquitto
  path: ./kubernetes/apps/home-assistant/zigbee2mqtt
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant-backup
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: home-assistant
  dependsOn:
  - name: openebs-lvm
  - name: kopiur
  - name: home-assistant
  - name: zigbee2mqtt
  path: ./kubernetes/apps/home-assistant/backup

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wol-relay
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: enabled
spec:
  targetNamespace: home-assistant
  dependsOn:
    - name: multus
  path: ./kubernetes/apps/home-assistant/wol-relay
