<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pulumi" Version="3.114.2" />
    <PackageReference Include="Jetersen.Pulumi.TrueNas" Version="0.3.1" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
    <None Update="catalog-apps.json;syncthing.json;tailscale.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="compose.yaml" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>
