---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-storage
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/storage
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/sonarr
  wait: true
  dependsOn:
    - name: media-storage
    - name: app-template
    - name: technitium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/radarr
  wait: true
  dependsOn:
    - name: media-storage
    - name: app-template
    - name: technitium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/prowlarr
  wait: true
  dependsOn:
    - name: media-storage
    - name: app-template
    - name: technitium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/qbittorrent
  wait: true
  dependsOn:
    - name: media-storage
    - name: app-template
    - name: technitium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/jellyfin
  wait: true
  dependsOn:
    - name: media-storage
    - name: app-template
    - name: technitium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-backup
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/backup
  dependsOn:
    - name: volsync
    - name: sonarr
