
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **KUBE_CONTEXT**  
   * Kubernetes context used for cluster operations in this repo.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   */
  KUBE_CONTEXT?: string;
  
  /**
   * **TALOSCONFIG** 🔐 _sensitive_  
   * Repo-specific Talos config path for talosctl. Relative to repo root/current working directory.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   */
  TALOSCONFIG?: string;
  
  /**
   * **PROTON_PASS_USERNAME**  
   * Proton Pass CLI login username. Optional if pass-cli is already logged in.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://varlock.dev/plugins/proton-pass/ | Proton Pass plugin}  
   */
  PROTON_PASS_USERNAME?: string;
  
  /**
   * **PROTON_PASS_PASSWORD** 🔐 _sensitive_  
   * Proton Pass account password for non-interactive login.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M2.474%2017.75V24h4.401v-5.979c0-.582.232-1.14.645-1.551a2.2%202.2%200%200%201%201.556-.643h4.513a7.96%207.96%200%200%200%205.612-2.318a7.9%207.9%200%200%200%202.325-5.595a7.9%207.9%200%200%200-2.325-5.596A7.96%207.96%200%200%200%2013.587%200H2.474v7.812h4.401V4.129h6.416c.995%200%201.951.394%202.656%201.097c.704.7%201.1%201.653%201.101%202.646a3.74%203.74%200%200%201-1.101%202.648a3.77%203.77%200%200%201-2.656%201.097H8.627a6.16%206.16%200%200%200-4.352%201.795a6.13%206.13%200%200%200-1.801%204.338%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://protonpass.github.io/pass-cli/commands/login/ | Proton Pass CLI login}  
   */
  PROTON_PASS_PASSWORD?: string;
  
  /**
   * **PROTON_PASS_TOTP** 🔐 _sensitive_  
   * Proton Pass TOTP for non-interactive login.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M2.474%2017.75V24h4.401v-5.979c0-.582.232-1.14.645-1.551a2.2%202.2%200%200%201%201.556-.643h4.513a7.96%207.96%200%200%200%205.612-2.318a7.9%207.9%200%200%200%202.325-5.595a7.9%207.9%200%200%200-2.325-5.596A7.96%207.96%200%200%200%2013.587%200H2.474v7.812h4.401V4.129h6.416c.995%200%201.951.394%202.656%201.097c.704.7%201.1%201.653%201.101%202.646a3.74%203.74%200%200%201-1.101%202.648a3.77%203.77%200%200%201-2.656%201.097H8.627a6.16%206.16%200%200%200-4.352%201.795a6.13%206.13%200%200%200-1.801%204.338%22%2F%3E%3C%2Fsvg%3E)   
   */
  PROTON_PASS_TOTP?: string;
  
  /**
   * **PROTON_PASS_EXTRA_PASSWORD** 🔐 _sensitive_  
   * Proton Pass extra password, if enabled.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2024%2024%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M2.474%2017.75V24h4.401v-5.979c0-.582.232-1.14.645-1.551a2.2%202.2%200%200%201%201.556-.643h4.513a7.96%207.96%200%200%200%205.612-2.318a7.9%207.9%200%200%200%202.325-5.595a7.9%207.9%200%200%200-2.325-5.596A7.96%207.96%200%200%200%2013.587%200H2.474v7.812h4.401V4.129h6.416c.995%200%201.951.394%202.656%201.097c.704.7%201.1%201.653%201.101%202.646a3.74%203.74%200%200%201-1.101%202.648a3.77%203.77%200%200%201-2.656%201.097H8.627a6.16%206.16%200%200%200-4.352%201.795a6.13%206.13%200%200%200-1.801%204.338%22%2F%3E%3C%2Fsvg%3E)   
   */
  PROTON_PASS_EXTRA_PASSWORD?: string;
  
  /**
   * **UNIFI_HOST**  
   * UniFi controller/base URL for read-only network inspection.  
   * Resolved from Proton Pass: pass://Personal/UniFi/Host  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M24%2021V9h-2v14h8v-2zm-4-6v-4c0-1.103-.897-2-2-2h-6v14h2v-6h1.48l2.335%206h2.145l-2.333-6H18c1.103%200%202-.897%202-2m-6-4h4v4h-4zM8%2023H4c-1.103%200-2-.897-2-2V9h2v12h4V9h2v12c0%201.103-.897%202-2%202%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://developer.ui.com/ | UniFi Network API}  
   * 📚 {@link https://varlock.dev/plugins/proton-pass/ | Proton Pass plugin}  
   */
  UNIFI_HOST?: string;
  
  /**
   * **UNIFI_TOKEN** 🔐 _sensitive_  
   * Temporary read-only UniFi API token. Prefer short-lived/site-scoped token.  
   * Resolved from Proton Pass: pass://Personal/UniFi/Token  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://varlock.dev/plugins/proton-pass/ | Proton Pass plugin}  
   */
  UNIFI_TOKEN?: string;
  
  /**
   * **IOT_WIFI_SSID**  
   * IoT WiFi SSID to attach to VLAN 20.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   */
  IOT_WIFI_SSID?: string;
  
  /**
   * **IOT_WIFI_PASSWORD** 🔐 _sensitive_  
   * IoT WiFi WPA2 password stored in Proton Pass WiFi item.  
   * Resolved from Proton Pass: pass://Personal/The Creep Nextdoor IoT/password  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://varlock.dev/plugins/proton-pass/ | Proton Pass plugin}  
   */
  IOT_WIFI_PASSWORD?: string;
  
  /**
   * **TECHNITIUM_HOST**  
   * Technitium DNS admin URL from Proton Pass.  
   * Proton Pass item title is currently "Technitum".  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M24%2021V9h-2v14h8v-2zm-4-6v-4c0-1.103-.897-2-2-2h-6v14h2v-6h1.48l2.335%206h2.145l-2.333-6H18c1.103%200%202-.897%202-2m-6-4h4v4h-4zM8%2023H4c-1.103%200-2-.897-2-2V9h2v12h4V9h2v12c0%201.103-.897%202-2%202%22%2F%3E%3C%2Fsvg%3E)   
   */
  TECHNITIUM_HOST?: string;
  
  /**
   * **TECHNITIUM_USERNAME**  
   * Technitium DNS admin username from Proton Pass.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   */
  TECHNITIUM_USERNAME?: string;
  
  /**
   * **TECHNITIUM_PASSWORD** 🔐 _sensitive_  
   * Technitium DNS admin password from Proton Pass.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://varlock.dev/plugins/proton-pass/ | Proton Pass plugin}  
   */
  TECHNITIUM_PASSWORD?: string;
  
  /**
   * **HOME_ASSISTANT_HOST**  
   * Home Assistant URL.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M24%2021V9h-2v14h8v-2zm-4-6v-4c0-1.103-.897-2-2-2h-6v14h2v-6h1.48l2.335%206h2.145l-2.333-6H18c1.103%200%202-.897%202-2m-6-4h4v4h-4zM8%2023H4c-1.103%200-2-.897-2-2V9h2v12h4V9h2v12c0%201.103-.897%202-2%202%22%2F%3E%3C%2Fsvg%3E)   
   */
  HOME_ASSISTANT_HOST?: string;
  
  /**
   * **HOME_ASSISTANT_TOKEN** 🔐 _sensitive_  
   * Home Assistant long-lived access token from Proton Pass.  
   * ![icon](data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2220%22%20height%3D%2220%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20fill%3D%22%23808080%22%20d%3D%22M29%2022h-5a2.003%202.003%200%200%201-2-2v-6a2%202%200%200%201%202-2h5v2h-5v6h5ZM18%2012h-4V8h-2v14h6a2.003%202.003%200%200%200%202-2v-6a2%202%200%200%200-2-2m-4%208v-6h4v6Zm-6-8H3v2h5v2H4a2%202%200%200%200-2%202v2a2%202%200%200%200%202%202h6v-8a2%202%200%200%200-2-2m0%208H4v-2h4Z%22%2F%3E%3C%2Fsvg%3E)   
   *   
   * 📚 {@link https://developers.home-assistant.io/docs/api/rest/ | Home Assistant REST API}  
   * 📚 {@link https://varlock.dev/plugins/proton-pass/ | Proton Pass plugin}  
   */
  HOME_ASSISTANT_TOKEN?: string;
  
};

type _CoercedEnvSchema_ba1370f6 = CoercedEnvSchema;

declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<_CoercedEnvSchema_ba1370f6> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<_CoercedEnvSchema_ba1370f6, 'KUBE_CONTEXT' | 'PROTON_PASS_USERNAME' | 'UNIFI_HOST' | 'IOT_WIFI_SSID' | 'TECHNITIUM_HOST' | 'TECHNITIUM_USERNAME' | 'HOME_ASSISTANT_HOST'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

type _EnvSchemaAsStrings_ba1370f6 = EnvSchemaAsStrings;
declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends _EnvSchemaAsStrings_ba1370f6 {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends _EnvSchemaAsStrings_ba1370f6 {}
  }
}