---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  postRenderStrategy: combined
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Pod
              name: konflate-test-connection
            patch: |-
              apiVersion: v1
              kind: Pod
              metadata:
                name: konflate-test-connection
              spec:
                containers:
                  - name: connection
                    resources:
                      requests:
                        cpu: 10m
  chartRef:
    kind: OCIRepository
    name: konflate
  releaseName: konflate
  values:
    resources:
      requests:
        cpu: 5m
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    config:
      repo: forgejo://forgejo.jetersen.dev/jetersen/homelab
      statusChecks: true
      prComments: true
      publicUrl: https://konflate.jetersen.dev
    secret:
      existingSecret: konflate-secrets
    persistence:
      enabled: true
      existingClaim: konflate-cache-lvm
