apiVersion: v1
kind: Secret
metadata:
    name: konflate-secrets
    namespace: konflate
type: Opaque
stringData:
    KONFLATE_TOKEN: ENC[AES256_GCM,data:cPTK/UO9tiPAcao22VkyfNAh1ZRo83MKpCH6eCUEiFejiQkDJbfpgg==,iv:qoJhRXZAVZx7dbUZMs/Zx05Dum0qgEiuAySQozDcsGE=,tag:thtr2E7pwAJyPywXBs/kzw==,type:str]
    KONFLATE_WRITE_TOKEN: ENC[AES256_GCM,data:leorXX+OFz7nvjZgW9JB07Qa03x8ROvAr1Zt4wWSnzuOKkTrRnQoLg==,iv:yxDmC5N+TblxUl4I8ViHgvCt9E2xFWD2SHoeg53KLrg=,tag:BoiaEDd/RgICIx1/TiyN2Q==,type:str]
    KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:/Faaf5FIa3qtFjDuZT5kveDO7WP0O4zSR9GZ2xpnItIAqTo+RFMm86T432xEWqxES9NTH92f+f9UEV/IohQeAA==,iv:WtXk/F1k22/taNMJGtdPTG5eAhqiYlLzZ9o+qyJTadc=,tag:/7bEl2OgMszMQO52ssyTRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlejB4MUZpMzdjeVVCQ1Q4
            amt3eWtFQkV3RDlRRjUvclVoOE9yM0ZJZlVFCld0U0xiRmorWFQwQXNBRzEvWGxi
            QWlGT3gwQ2FwT091dzVuQnVFM3QyV3cKLS0tIFVSNTFPYVlaVlU5S0tXWWRPcFUv
            bzhIRDdRQkVhd0xXUmR0QWFwbks2TncKkmhzMBkn69tQRbEDw02LyS15iTEG6qV0
            3oxD7gbHCbTSyOJO72SIC1in1wexTSv4KnD8KRvKSDO63x81TF1uSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T23:08:59Z"
    mac: ENC[AES256_GCM,data:9ekicqpmT3RZoAqF4V82MRuGcZysoVsfvqcN6C3iMyNPX4+92tjS8PXu8nj8oflujz4X/VZn/HrgVnJDE4a5qYXLBXBgbFCV/qxn4ZAyvsESZzdWCB/ozZAwLEpMiti4mKwCMf8M+Ns48+3N8d6AnWDa6WZ0t2oDX0LpG3V5B8E=,iv:uD60sfGeJ8I5UqkWwxmGxaVsnC2fMTqMNagUiLXrTw0=,tag:jtyFvgeVj41t8eFMBIvXhg==,type:str]
    version: 3.13.3
