apiVersion: v1
kind: Secret
metadata:
    name: konflate-secrets
    namespace: konflate
type: Opaque
stringData:
    KONFLATE_WRITE_TOKEN: ENC[AES256_GCM,data:BZfNCMFJiBpU1M/JybdGqaVspFRAVmPPBC2Ff1PIPIRKeL6Kb5X85lXL0J1luCmUr4p85XkYaLiMkXeSIty82+GiIOVcp1rppLTSpgrS2OUdnp7ygUt1wFmLIpJV,iv:RPsn67JYAHG6gkZnubQ4VjUePvaxZne4PSfGf6bxy5M=,tag:TEETGJmosGGoVo/NpHsVBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrU2NqWmpFb2xscWJGVUt5
            ZVpJb2UzaUhEcXV6WE1zV2ZKL1YyT2l0aTNjCk1ycFBpUXFLRE1pc3JYV0FZRGFE
            dStVdCtpLyt2c1RmZkE0eitTWm80bUEKLS0tIGwza2ZKRGVhakJMYzdLWURTOVNl
            dms3ZmRQRVNSV1lnZTlhVUpkTGdVbkkKcofSdXnSERomDskFrrks0BavULo/FX1s
            gKEqypBKM34DVyMZmJAOSPVHJ1r5WaPJ3q3XbR/gDU2gKJi4HfieWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T19:56:40Z"
    mac: ENC[AES256_GCM,data:WV81q5QxXrlSYgJP+kgr2k6zAGt6eqcdVp2J/+6m8+vuSsuDUbdXpu5YioH3qMaO+Ik3iCF0KgylLP9BUzB8v+nkHqPN3rD6qzfuRMTI4MLWaGoV3XC4PG+TQHno0+ugzJLC64uH0rJMdgizG0akwNPuz5C4EeBasJyYxNp7uY4=,iv:FRvO10FnSQ6/lNdrjF/eXTC3zonraHJgW65QwpiZ4/g=,tag:jayamePrVwcQA5o5luLn7w==,type:str]
    version: 3.13.2
