---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: secrets-sync
  namespace: flux-system
spec:
  interval: 1m
  ref:
    tag: main
  secretRef:
    name: homelab-oci-auth
  url: oci://forgejo.jetersen.dev/flux/homelab-secrets
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-sync
  namespace: flux-system
spec:
  interval: 24h
  sourceRef:
    kind: OCIRepository
    name: secrets-sync
  path: ./
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
