apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forgejo-admin
    namespace: forgejo
stringData:
    username: ENC[AES256_GCM,data:IILrwxukFEI=,iv:ZKofuVK34iyVJwP4GcmomPFzb7fEud4jEmtcAPbNFlI=,tag:p6/qFB6mNzU/EkqHk8cRuw==,type:str]
    password: ENC[AES256_GCM,data:wT/UGRJp8ZS8JkJu4oDXQjZad95f9Y0KF7AyQobrieAl5kokI/zcNTTWnQ==,iv:hi9MR6KrDYqJkukYbGwwzDvUURn2V45ik4AAU2XlE5A=,tag:LnEtaiR6o+kKKrryhiWt8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcUZ2cXNjYjJmSFYvVVI3
            TGozNEUvVm05ODFaaTgzT3NLWThCOGdNbHo0CmtoUnNFY2lPclJGdHlKVHl2Q25u
            YmFSdWtaQ1VtcnozZHd2WDVKRG5DeVkKLS0tIHh4VVpqR1ljbTV0M0s1bXlpWUFq
            WHVscTlRT3VDUlA5Yzg0ZVV1ZXVhR0EKfRbugY5jcuQa2vJB8n8cHKLqReTYuLDV
            fqCLWRum5ROvLNxq7p4g1O4K3IqNrpNZPTu8TYt8aCwqL5rf5DfLzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T11:43:33Z"
    mac: ENC[AES256_GCM,data:OFAW72vDQ+ZmbAoiWw0GZCJnhIjCzuqMDsBi6H/nn1JpIZv/Un8BuFMI8ffZjX/BwTOv/QHzfIKKXjHDru7vXirwmL6nCq77q9yMfAOzrCztd1YpgUdxFUa6xWqnsL+vyjo51g4njs9RTpj23y12gD1ds4BHFdbGVI3By7/gzfA=,iv:GDSrZ5ESRIlj32fogKGY/Cwwct2MjGeuxknbGp7AftI=,tag:aK9Syi7yASbM0zXHFeK8RA==,type:str]
    version: 3.13.3
