apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - source.yaml
  - helmrelease.yaml
  - storage.yaml
  - nas-storage.sops.yaml
  - admin-secret.sops.yaml
  - access-policy.yaml
components:
  - ../../../components/oci-source-defaults
  - ../../../components/helmrelease-defaults
