apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-local
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
