---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  releaseName: tailscale-operator
  chartRef:
    kind: OCIRepository
    name: tailscale-operator
  values:
    operatorConfig:
      defaultTags:
        - tag:k8s-operator
    proxyConfig:
      defaultTags: tag:k8s
