---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tailscale-operator
spec:
  ref:
    tag: 1.98.4
  url: oci://ghcr.io/home-operations/charts-mirror/tailscale-operator
