apiVersion: v1
kind: Secret
metadata:
    name: homepage-truenas
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:/VEoZb0L1xgw2GyXHrAjycDoJvtV1EMzfmIqTkvhI4/q841p+DV/gqIbEpkWLZIFYUizGtXe+Oi4yo7YbhW7tjIo,iv:A2H8swis465EOiuKaZR9dlun/j/rOSdJd8xmpUPVjAw=,tag:zmeU+EJh60F9lOtilGxe2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM2RKZ1NLdUpWWFFhSDBm
            aVRkSjU1Vk5PMmNqejFTQ21taFBTaElIRjJRCk5zSnFVc3RXZy9COXU3VzZzTHdw
            dmFVaXI4ZVhjZ3pBRVgvSU9Cc2FJaEUKLS0tIGhSbmErQW8yWU1YSmFjRDhBajhj
            TE53TWM5TDRGQ21VN0xGN0s5eUJMa0kKZFOU6jZyeazTOaB5joaV6JI3hxEspFI8
            m9amw9zN7pZqwzJzbC9uvRKJ8DWvIh8II7uPd0SRWL79kZMllEVKpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T18:10:32Z"
    mac: ENC[AES256_GCM,data:2JDBiZAsLHBT7AiI11uOPyMOd8FuE7mJZu4obweiHlBpOoiUA+7md5zCEkSEdgGAAZnjS3d/aBUYrGqkwLPqIJ24/hlmZIaB75muCrfC8ni1yKPKSOm4VCA6vikLN+WhjgSnLAu4YCMx1IScgLfXHtZwKUjTLZOKmFDfy5bcPJc=,iv:dwdydTdSJdtatIE0HDj6B/o7BGWNXWQuuVuQ6X0XYEY=,tag:9Y8HbbW8ZZ3bRKQz16aX6g==,type:str]
    version: 3.13.3
