---
machine:
  env:
    GRPC_GO_LOG_SEVERITY_LEVEL: error
---
apiVersion: v1alpha1
kind: KubeletConfig
config:
  imageGCHighThresholdPercent: 65
  imageGCLowThresholdPercent: 50
  imageMaximumGCAge: 168h
