---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glkvm
  namespace: cert-manager
spec:
  secretName: glkvm-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - glkvm.jetersen.dev
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
