apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config-lvm
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: openebs-lvm
  resources:
    requests:
      storage: 1Gi
