# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
data:
    wg0.conf: ENC[AES256_GCM,data:/7CxDRAPo+4x3Y3h6jd7BvM4L/mJpItz/WX+BYg/aoZPKDSvHcgPtmYWqSdxp55FgiENWOJXSWGokenOJnIzQ5ibxrULyoGFq+1GSTGfeZE7zPdax9tjad8vuL0GYXvV/rWLTkh9IF+I5JP9/1XrsplEFcjkZxOMe1eHOhiq3M2gRZTyNckVc5NA8E+ZxJHK/0VlqxRRbKuXYmBTc4fSjo0iKdRGiNYaWbmqQ+TvNq6VdUpWXEu7YOZG7YRojl7rBra89mW6VkW8J3RymU/XLRwHMTNcn/MvCOV2/rNNqqoqgq2CGMA6Juj4xawe/n2u/BO4lCnOtQfv6jiv3GqCJ5pj1U/cxMbF+56kEGpXVx8xJOZZ/VHyx5uXuvmO0SAUSpjiMaiN9ibrPMJYN8157/dX9uzIbAQIbE5UpLLpa3lHeGNPFaN7PDS0us8DSfXzUO+Z3bRb8JMKIe9C2Pf+4XNIotTc/t1V8bZB8Y/6lsGNtnnUdp8odM3Pedav1u3n68QbMf1a1jXJC5VmSs9c+TyvKZRInb/gBH/ZsJ4G04lgmRbaBwsBua6KRQhWgO4MGf9CVIBP/wqI/a5EbuHAzxMUd2RQxCzHtYkn6xmkSt8Fc2+01ntTzTP4Zy6kO/GyxB0ZR/htmWOvEwLLv3le2cONI85ph3Jy/Zzz1O0mEDxPV3FH5toMc6tsQQpVq/Pyanp4AlCYVxSnI3kBrVXq/B5oKcdOZUlUs2rFeBRMhJEhtwXHUoqfd1Do9cm11qORP9GDNhS+/UApRLbQQbGlovata9eg/78wXeJmUgR4jW2z7f7XjaZ1h88B+YvPv8xFtshDKk4U0Mv7f0PyeMJp/89rR2VPl7HyrDN3zvpYouZoQ+3GBue7qv4m+yWYtIAwpaZKdDsOzTsl0PsSzZvGEhiD5X9xUKSGAoFbCkL2M8ypuAr8CGpCk3YYCjbchCQF,iv:pOmXP5Kf2oQ+xsEbOaBCbglSplH7Y934qBzJIfXFBUk=,tag:rQXPA0Ag4EB+ZTLSY8cUTg==,type:str]
kind: Secret
metadata:
    name: qbittorrent-wireguard
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU2pNMHJKVDhBRU9lS1lT
            REswVVl3bE1pR1JiS1N3bTJQUERtL1A3SnlNCm9UYzlmc0tIWXRQaXpSbDBxczhs
            amVucnlGdHpSNi9RVXR3U2w2c1RHVTAKLS0tIFdMYWRYZlk4RmwvVHZvT3Y5SGtC
            c1RHRW94cUc5dXRRa0RGYVdQaExFU3MKRma0K/PFP3Gxz5TNJUEkBcf7FSxWRLgD
            V2Yc18EakBWsM3lE/AeABGjoQZU/b4L3M+9gkYiNtmV9tPmkKGUh1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T18:39:09Z"
    mac: ENC[AES256_GCM,data:kSYDYZ4rglLj3H8cqI3ukw0ctNzH35zuvl1uiN+SSR6vTR742iW/bK9Go5olN7dVPpLdIepy3ONNZQiQvVuAF+WcQFXhR/AD9La2GjiQ67NEfhhrCWHrAFhr+x7KwPINYbGiByzx1YHFhilE4ahBjnotd40uCjIo9ZDBwKH6ycw=,iv:8LtMrXTYTPH8gppJtF4SeT9ZS4PSO2L1Oc2JrEKhMo0=,tag:A5dBIjDoj4wf+oMBaB+Z9Q==,type:str]
    version: 3.13.3
