apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forgejo.yaml
  - adguard.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - home-assistant.yaml
  - homepage.yaml
  - konflate.yaml
  - kopiur-system.yaml
  - media.yaml
  - monitoring.yaml
  - openspeedtest.yaml
  - reflector.yaml
  - technitium.yaml
  - towonel-system.yaml
  - volsync-system.yaml
