- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: homelab
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
