---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-template/flux-ks.yaml
  - cert-manager/flux-ks.yaml
  - cilium/flux-ks.yaml
  - coredns/flux-ks.yaml
  - envoy-gateway/flux-ks.yaml
  - flux-instance/flux-ks.yaml
  - flux-operator/flux-ks.yaml
  - flux-operator-mcp/flux-ks.yaml
  - grafana/flux-ks.yaml
  - intel-gpu-plugin/flux-ks.yaml
  - kopiur/flux-ks.yaml
  - local-path-provisioner/flux-ks.yaml
  - kromgo/flux-ks.yaml
  - metrics-server/flux-ks.yaml
  - multus/flux-ks.yaml
  - notifications/flux-ks.yaml
  - technitium/flux-ks.yaml
  - towonel-operator/flux-ks.yaml
  - towonel-operator/tunnel-ks.yaml
  - tuppr/flux-ks.yaml
  - victoria-logs/flux-ks.yaml
  - victoria-logs-collector/flux-ks.yaml
  - victoria-metrics/flux-ks.yaml
components:
  - ../components/flux-kustomization-defaults
  - ../components/flux-homelab-source-defaults
  - ../components/flux-wait-defaults
