# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lvm-storage.yaml
  - helmrelease.yaml
  - httproute.yaml
  - source.yaml
components:
  - ../../../components/helmrelease-defaults
  - ../../../components/oci-source-defaults
configMapGenerator:
  - name: homelab-alerts-dashboard
    files:
      - alerts-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: homelab-control-plane-dashboards
    files:
      - dashboards/apiserver.json
      - dashboards/kubelet.json
      - dashboards/etcd.json
      - dashboards/global.json
      - dashboards/namespaces.json
      - dashboards/diagnostics.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
