apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - source.yaml
  - infrastructure-scrapes.yaml
  - blackbox.yaml
  - probes.yaml
  - monitoring-rules.yaml
  - backup-rules.yaml
components:
  - ../../../components/helmrelease-defaults
  - ../../../components/oci-source-defaults
