apiVersion: v1
kind: Secret
metadata:
    name: paperless
stringData:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HG72R6s4IplBnsA45Dt9Iw==,iv:SrxTZGnBXf+pT67qLtousapZHRlvWa3+x9rLEMQkouM=,tag:iXXc3rwfSNxu/hf/CHQQAg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:gUf4dTxE5cNqLsQIHWCno6DP2Hhm46jFMhh3GXWb2+AMIHu0q6AjWg2Ad6Kowb0ySPYT7ziBsHI9QDlO9N0pw/Zs9ZTSDjdNrAaxqCmbLbbBUp2hqA4=,iv:qxy1r/jf+lUSham736YHLeQ8Gh//OUhlesssnilBOl8=,tag:99FlqgxZn8fCxUCC9bO3cA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRm9MRnBNYkxGWUQyMnhS
            S1JJVlhVZVllWW02U0FJYnE5bmJ5NFJ0TkZNCitUQ3JNdVBLd2wvNWZHWVlud0lq
            dTdld3pKVy9UaXY4SXJ2S1d2dDNlVGcKLS0tIG1KQXp4NElUdEJSckp2QnNHWSsz
            TnJSZG0wRHVyMC96Kzl0NGljcGhhejgKIyCrwBa3Fx37q9j/qN4lmMUAnhIgRfks
            12QI+CYeh7i9FsHsHUmV6yOC1N5ez7acG2Kv4Ig9CJFbkenqAWyRcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T15:21:43Z"
    mac: ENC[AES256_GCM,data:Drtn3LqRbAheWaMQMISaW9R9WJyDj3Xluf80yzNzhserzSNHtBGpqECJH9kG4qKroKRb/kt2p9iKyc2snwWnOypfzlScvqA2X+eUcoV9v4gHWRutnmDL2J1lCP5fvZcPHx9yO+YWeztaDl9EcxUTXWcTygX85ypfhznpsHVQiy8=,iv:k8Cv+6q8x1HCMkR3z5IqRG2S6yZVKj2viQipcOFZA4w=,tag:QoFK0oQx/Ud+9FhT9JZnvQ==,type:str]
    version: 3.13.3
