---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      version: 0.3.65
      sourceRef:
        kind: HelmRepository
        name: pajikos
  values:
    controller:
      type: Deployment
    deploymentStrategy: Recreate
    hostNetwork: true
    hostPort:
      enabled: true
    persistence:
      enabled: true
      size: 5Gi
      storageClass: local-path
    service:
      port: 8123
    ingress:
      enabled: false
      external: true
    additionalVolumes:
      - name: home-assistant-secrets
        secret:
          secretName: home-assistant-secrets
    additionalMounts:
      - name: home-assistant-secrets
        mountPath: /config/secrets.yaml
        subPath: secrets.yaml
        readOnly: true
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 127.0.0.0/8
        - 100.64.0.0/10
        - 100.65.0.0/16
      templateConfig: |-
        default_config:

        http:
          use_x_forwarded_for: true
          trusted_proxies:
            {{- range .Values.configuration.trusted_proxies }}
            - {{ . }}
            {{- end }}

        frontend:
          themes: !include_dir_merge_named themes

        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml

        rest_command:
          unifi_wake_on_lan:
            url: !secret unifi_wol_url
            method: POST
            verify_ssl: false
            headers:
              X-API-KEY: !secret unifi_token
              Content-Type: application/json
            payload: '{"cmd":"wake-on-lan","mac":"{{ "{{ mac }}" }}"}'
