---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - glkvm-certificate.yaml
  - helmrelease.yaml
  - httproute.yaml
  - secrets.sops.yaml
  - glkvm-auth.sops.yaml
components:
  - ../../../components/helmrelease-defaults
configMapGenerator:
  - name: home-assistant-notifications
    files:
      - homelab_notifications.yaml=notifications.yaml
      - glkvm_certificates.yaml
      - glkvm_certificate_sync.py
    options:
      disableNameSuffixHash: true
