apiVersion: ENC[AES256_GCM,data:doE=,iv:7ZLHRe90GHk6eTLj3Gk6EV2wzR3RqpjhY2kajtGzmGI=,tag:xU/YshGkuZZWyRIa4mdZkw==,type:str]
kind: ENC[AES256_GCM,data:l9+geLyz,iv:5SPDPQg9tsSjCu49WhObaUZYxbe8bFCZL2WhhVvMvvE=,tag:4OZ4R1Mn0K9N/PURt6cMlA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Sy01F7uuIYS78yfropuI3pzl0rhs6Q==,iv:K1wmEBy1Zs2Gdjod80vhse8sV/ZJKnwNt1BKc0SIshE=,tag:bNBnV+Glv2w8hdUSMCvUAQ==,type:str]
    namespace: ENC[AES256_GCM,data:VkaNUrzLHsgennmPOgo=,iv:6RHYEeUpvCf7ri6UmOYuyV8vCfPE3HhJgmE/g2Vs5R4=,tag:YIa+0Erpj1iR2LYKuI5XXw==,type:str]
type: ENC[AES256_GCM,data:dXjXhcav,iv:F+QQDSyaXQ7JpcnM0Iz8f4k4IKW44d/7EiAjj2W+Kb8=,tag:ROspCmvxu5jm5ftlKFwg9A==,type:str]
stringData:
    secrets.yaml: ENC[AES256_GCM,data:rE0TdMf6L/P1TCaB7l0HMCXL0wYASuhbI5bQCWnRJJNOGaBarLb2Z7LR489iHNvNZJhz4Av3v3oTUX9W1smTT//HxLprxDo2bn7H9VnrD+hmGqosA54GQgZXmXKlOfj+vi5tJs5DmYPn2EBK0Ay17Fwq/2JRwwugEGQoF9lzBb3X1fx2gsLi7qFXBpClPklEJ3k=,iv:XPAZRY0u0A+wnZPPDNisnIKswSFEgeWhVpvon9mlDLc=,tag:CkwI9wc+XKg0GZhB86d8gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SGc0cnNwOUkyVUpoLy9z
            Y2RyQ0J2M0FLK0t1UDlBV2E4UnYzR0lqVUVvClI1TlkzRE16TEpHQmZwVzlNWWpj
            N1d2MysvcWE4a3B0ei9ZZUg5VEdwSVEKLS0tIFBiWldObDZ5RERONXU2V3dUcjR1
            WnlPY3JRRnE5ZmJESWVTZ2FlVUprclkK0s7tdRx07YYHj6oKdhsJN5ypeCZQH1/+
            izcCbvk/d3hWy7iPYjjZ0FI3UAx1frBfPW7dWSf9rdQ53HwjxpycAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    lastmodified: "2026-06-03T23:02:18Z"
    mac: ENC[AES256_GCM,data:u51/o4u1B2MsK2Vo58AMAo6mM8GO0kSLJrtGyn7QIvMTTn3ApbiRPslblLKrqLnLBiwfpUr5SPyh0cveWUMpw/+9aZUN9q7gPGWGhInl+K/jKLzqBUkpv2Td5uQaLxlWUA8TpW60k23hQP4HYrFvwu6omqHyp1kXgvP5e464F3w=,iv:s06eP+fh+JijER9iMrmsBBMZgd6ike+xqKGGf5h/XZk=,tag:QUObdCIdtruOo/MHQkJKWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
