apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:Jp0vGbJ1HwBnLQRPN8IOnpuUbIK9lTV/BO5C/Utkam+OVVutX17QcBlmibchatwrNP5vUtpRUmVaK+2MQQT9MzTAZZ0GgzqI0tu9noe59bJhQhccX4ck7YKT5mlhnI3jgLHx31ebGOJZOO2LckXFw4heS6hW2J6FHEbl25z90DgF7Ba5DPQrmjcm/5lFFAYW1y8=,iv:kCouI162S/qqDsJfN+padOYD+MV7+oeXmXnODQiu6UY=,tag:0o0Gro3w+qkJoIaGZBGNlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTnoyS3RwY1dMSjg1K0Q2
            aGFDWWt2RE1ZTUVadnRnUkNKa2hPREc4ZUhjCkhKdDFEczJrZjVzTnQ0T3NucXBy
            NXNHY0llV2t6VHo4SVFlZDFBRTdYK2MKLS0tIFZLd21aRkQrdUwvOUNFVTBxZlc2
            K0hxWnpXa0prMlNwOGk4ZHRpVTNaQVUKp2vAc2SJngTHbTUXyio2ivK75xF5QAMU
            zeGOJA439o4V936tSyPHaI2rx5CbbvoklMcIimEAR0pFETV9xCW/nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T23:14:29Z"
    mac: ENC[AES256_GCM,data:k3KQA7CC3CDG2ppxcQ41/HET+vnwHzCPnqdr1g5qbQeAgpPveIjlxKMQIvx4bvgdxzA/fIlrFGn4xxOCFisHJq076MAH/iHdXorn0gzfWDfhDWTQbLEeHTSnGiNLcETo9wh7wFHHw5XT/QjaATCEVrURBugbbVDvupOvFbiqecw=,iv:+9yP4S5XOWX+CrPi6zlP2/z65Py2JstDx60iwcFiuOs=,tag:mik6ZoIRVpF79SUZRefqQA==,type:str]
    version: 3.13.1
