apiVersion: v1
kind: Secret
metadata:
    name: photoprism-kopia
    namespace: photoprism
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:KS7Bh/UobHHouqj0tZV0/AxD6sUdi9HBHebb4pkJtp9hq6N5YcDH5J+d3UMU4lm7erhxpQQf+DmgI+bH8bA4IA==,iv:gNy0FkwHsJaZn2YBH1Uv7jAfT0K/o9DRBV/KX56ZTlM=,tag:MFs0eMQl1xdUgRrugfttdQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4joupHWSOketsEBp4Z6lsg02EwLvfckB/Mg0eS6tC54=,iv:tAQ7iVYEVtICHHHU7t0ITTcevNBxCyJVkSe+Z4VEBx0=,tag:l54QdAu0uLcjA2MDPOad+w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/fs5TrRIVxHYGSchomn9lLnds5GG0hkWSm13dDVYRS4=,iv:E49xI0inA7mSYWKgTGJ/ZZKgwBPncG3/g6rFjX7DMGM=,tag:ZNIwrtQ8OGHOwuNKM+Q33w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TTAyOER2NjVKUkMzTHpN
            TGh6ZkFVLzNvcTU0UG1LSENhMWdGNnJpZm1BCmh0RlNqdFlnUTNGd3QwSXhUR0R2
            eE5TMW9qdTk2cUFhUEZBRWQ2L3BRVDAKLS0tIDloeFlCbmtHK2NLbE9WTi9RUDdx
            YWt1eDZoeVFIdzE2WFp5OWtjQWJRYmMKkdTcSfeL4cPQvABUY6AMVmr3t+dcvzko
            3E6qZW6UvyWxv6aFxB3jcH07xpJ2NusrFLa8TsHB3G8m17ue5dC6vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T17:25:52Z"
    mac: ENC[AES256_GCM,data:tfyUI/5DhuSlbYrtoMQOglscQp+SrwksyVquvEg6OpHYt4hOAh52ndANWTkajpwPcRHVD6rv9/yEfnpSbtDqagB6jAd9v0nAMIFHRcGf2Go8MMDh9mSfUaMIrLkYSZWvXXqNXG0X3CIL3FOFznTfwcldNLmFWwLoPw02evARBnI=,iv:uNSLeHJWpSfnFmvxO9RXQ8VmtepN7zuLbW8V6CUWf1w=,tag:WNLSy0/B+B35Q5tJBmIMgw==,type:str]
    version: 3.13.3
