# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-kopia-nas
    namespace: home-assistant
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:3yPNI8NEBoXtStNnId3pVdx1/gGK/rRyDKUkMnUlC6g=,iv:TTUvDq2CVG7YRv6i257DSFb1EJFwmJXjnnAkONtbv3U=,tag:EO5pbKEeUPcBVWJg/cx3Zw==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:kyOXSjaSJNZNiyx0VAHDvtJTxi2lUKNiuStM2/QLOpfbWsZ4yo5AiHKUs4Ksm5OwkHOGAmVPpB3x+VQNP3J33Q==,iv:8d9EZNXT/TlMaUEBIq7ODZqfxhE/KkK+aA1292IVAZg=,tag:Q4+BvCNs0gDOcw3pXpGz6A==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:GKNU//8=,iv:BghtnrVvy4FsZ4yZr8WLDm8ld/Iy7yPE+TKlLy31uLg=,tag:9keXlhR8P3Pw/H29oTXmEA==,type:str]
    KOPIA_FILE_LOG_LEVEL: ENC[AES256_GCM,data:bdeUqw==,iv:JR5dlytwkgfLL62mgJtStajRI3INPQ/J07UL6OHZjRU=,tag:0zHY9p9eS5MC//2NxYAzrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OERpemN4SFl6aFVIbGY5
            L0NqVEtTWFBJWllTUDlHVUR0TG1BaEduT0hjCjNjSVM5UmNVRlFTeVM0NzRzQm95
            c1AyQjVnQzJhR1hZcCtmdTJJd1VmY0EKLS0tIFA3Nld3U2FIL1pSbkt2a2d6SENP
            UVUxZjFFN0sva1kvdlZsYU9QcEYydncKDzv8dEDWNBqeuPZe22SomQ+CfsNhQy8c
            z/J2WZdmPTQ3KCO38mvFJ5WkFEfyzdFCCVzRtI4b81zmXw9H1NY1Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T03:58:42Z"
    mac: ENC[AES256_GCM,data:6tb9zLT0VM9Jn9+ida2DSYYTYooSkVnz4MXO9UhKahREjfQ4IUYoyn1/8lPNG9Fy845h7iu7CLUVKmz+yMMOJklp3d4xdQblLPLtCt8fSdB2/Xs9knLW3qmeIxC/eWkpSy3NyZWsSGV+kMSuW9peed8faAcJ0weYR9sLarFOw2s=,iv:zaVjXAwrUvSLXb4DCsD4+OpRvtHv/sqJPDwzyKUaKm8=,tag:B+o2EdTXZ3K0cEAjd9a6Uw==,type:str]
    version: 3.13.3
