apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-kopia
    namespace: home-assistant
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:NKegGzL2h64YZb57o4flAY80Iiax2iXPqErYwvjPbA9FMBdwN8H6bMH1Nr2/Rxw5,iv:TPvYO6vYdpLHIA8220waRrOHV3nmCRbDwOyO+Net4/M=,tag:3d4NYhxHbE6IIlCy0iaSdg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:neyJYNwGhxGQGBdYH8TAKZh2Z+aK0SSNKpvQFvrjc7wNkCFOKFB/WPzkzXyd4Ap5TSTYztgbkG4Gcpmk5Mh0Jg==,iv:ju8X2YsBHG9DMysHIqkYOI7oBsAzI7z0n0sMgyxl29U=,tag:8/giC5UIhgMpQE1JGDG+LA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:i5Mi+0Gu1zzLRhRgmRCsBUZhX580yx3HvsqxZzRYtvU=,iv:ORlLZQKHR6UnySSSssrte1PKX2w5aWVfmtV1cUJC6zI=,tag:x3Twq9nBjnY5j7Iv8pzCXw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:l+j3V1yJVta27zf9oG9eIZqsFiuKqa3Zk0oObE5yvXg=,iv:yNREVXoc+rPtkct6csllEqbqL1fir8EhZYrXFQfCvW4=,tag:AjJzfYYBSRoV2+d8H9uI4w==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:cwU=,iv:Olg0bK2ZvI8NjythwTrWL+gTgiZ1zmBqYrDz1q4M1GI=,tag:rDe2qUnyRjD3tYUq1LURhg==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:UBX146Ap2AoH1d650CtxFuFBK9mwow==,iv:bFNnAQLoYxbOod2DT10Ksm4F+HoptZ+vKj3vWg6rBV4=,tag:UrLeDT2UXPvVYeRcEjfNUg==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:BNItnUw=,iv:n+zG/z06DT29v/QTBCZUTZlSzlTGGYqBHVV+Uh/Ad+A=,tag:M9GBR4AeuMS015pzbDgAbQ==,type:str]
    KOPIA_FILE_LOG_LEVEL: ENC[AES256_GCM,data:PoppXw==,iv:vp0VjU96D3TIB0U/h/DhFAjTqJmtyY80o3w/nEd8r/4=,tag:Fm8dZNvRUbmw9w/fnjevwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dmlBWXp5dk9pVHh3Yk5i
            ZVhHY3FEcDYybTBXZFRIREYzRWtKMWRGUkdVCkRvcVdGVzc0NFdTeEpPalBpLzE4
            Tm51cGRTemtrZTBReGhhNGVxc0orNzAKLS0tIFhJbE41ME5aVVlENkZnWE5SMU9S
            NVY5OTR0Z2xaT3k0RUhhT0ZQaVBXUlUKPp3odNfYUeeA4RaRpfX0akWj9NrtqRKX
            Ntnh7Wx3VcaRfRvqkSsepuxuQz1kAme33Q7UJXu16Z5ec3pb5d7ZFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T00:28:07Z"
    mac: ENC[AES256_GCM,data:jWqNNfw93UB38c7SPr27qbUrqwB7WJohaxKLimJKZsq3Kkc+ZdZBKnpfyslySR7eHijOMz5CC7rogrefeRvOhgy+TdokNDiX5sP61AGUNCXKmXB5paF5PEddbtue8cV+2A1qKtI2TGkXN9gALuncotfaSDn8jYqcbBRKgb73YJA=,iv:XADQfpdjbVIByX3IwGCNhpDF7tm+fyWzXdpFHisqL5I=,tag:8HAOpXYwymfs5wnTQ+ElMw==,type:str]
    version: 3.13.3
