# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-kopia-nas
    namespace: home-assistant
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:2M23QhFCUxoFJE7jbkh5k/DaH9JvryFCPKMT/UY7Vuw=,iv:M4qaHl9fhG8WT1SacW9eujrXbLxAVOj1vAXQSftq4HU=,tag:m22jjPgh894HIZqgPmeGHA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:whXU4IfmDTxjOAwPEw6gPdMMoSWqpq1Dz/ueTr5JabvJpeiE4QYMNS2GUmpa8BSOcqZmV5nYAXsa9ZGdGvOweQ==,iv:n7itlEp2nxRPOEQeWvwMQU0twn0JuHzP7oKQ5rSjqDQ=,tag:RZ0KlL5x6lV/DCpfVuhXDw==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:9o5ZmPA=,iv:1dd6ts73ElK9BQezOpccrMvk0bUsNy8aA27RPxYtbwA=,tag:FisWT0UCufW9IuvIyyZMTg==,type:str]
    KOPIA_FILE_LOG_LEVEL: ENC[AES256_GCM,data:JGc+Og==,iv:IZagI1HVJj1NZivw9Dhv5XYtVv3dlnw0rNqlKrre9do=,tag:JYrqlP5PEpN1CxOszKK0fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUWI3YmN4eFVURXNtWTVP
            RkdjNzN3WmZzMmg5M2Q0M2tKVTYzL3lDankwCjRCLzJJM1g5dmd4SnU1aDkrQXoz
            eHVsMVFxU2lNZjYzSXc1YlFBSG5ZTkEKLS0tIGNKOGZXOU1ZYWFuMGl6TFBNVWNG
            QVBncUtjVTNjTnhtemhWdUcway9VTEEKof2pbh884QqDr6zJzjiH52g0zxH3QvQs
            Rbpcus0MTsUZLVbSX8pu8KWSLskGJ4Xq0dEh1LSrlByJaN7WmFlUBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T03:58:42Z"
    mac: ENC[AES256_GCM,data:bfVMjKYGyOf8x9eQhFHkZ/4Mxxk6afXfgojX8i4dXCdcVOGa+QwDpKXX/pfkqpa6hGi0nVmgdZxRb1u31S3npX+n1m2Y6X4cQYzXYT77K9iOttjZQZv5d2MXswuhu4HoXCg74hijsMXu8I4kA0KeaCIbTLoGN/7X9xvpzufE4Kw=,iv:39a4NlLTzs3nP9ggUWeLmGbo4evonyvqebWPoRY4D8k=,tag:pVxBrASluJxn3yBd2NL4fg==,type:str]
    version: 3.13.3
