apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-kopia
    namespace: home-assistant
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:TOKc4jy45zOKe0Xyxm6bhfgvhRl3tnQjbG6zaev2Jewj6y4EG+5bLB25/5Nj,iv:WPIFn0U6D6NtJf2jdTG0+0CaM2PzL9kL3iwHDXlrQrc=,tag:cLzdgXVUoi+LVcOMBIWBrw==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:MyeAtNEtq0lUbRyvf8G4vyLxeST2PyPd40+Kfitoct837xveb9Gvp3rf67UW1j1xItL+Tr1nzQ9WyzR6QSvnUg==,iv:+T0FyCVFjL47fT630DOF6fxoloMzcKWy1TVkKwpCF58=,tag:ioyzJp1pq2HafFTVrLqd8A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qywG38T4jwqjmWvaIHJKrZnL91VTte3EnUkeGXlYVHo=,iv:IjockmfoX8CH15MUj0i8LzoqNbMkrTgjDNzx+ZUJR1k=,tag:VBLcJP97xNjdloOChAOJhw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sJKkjRRcI/tZOnfFdL25tU+IokeKX0ZDPgIrm5DOCcg=,iv:3fRDPZk3IgjgDbPC9H+moFtzKoGLwk7Z/I06FvSYt0Y=,tag:319HW8iye/Q5tTceiTrZ2w==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:5RA=,iv:aYhcI7gpuV/P7ysw4E8CkNtppTo4yXqSh/y7GNIxW0c=,tag:a1fBUmsJAOEqb4x6sZmz7A==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:lqyuG+6FW8OzPw6DsqUT4ZfWk1sTCQ==,iv:DaUbzMWqDOHEXkzIJLmqzqjOFGfsGwOgdlij5siB8pc=,tag:afASuySVS1yWWpzXOQEbiw==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:s1rhw1M=,iv:VTrQRE9YC/TWErswSesknlX4+QeX3l9DJCKcZve0/Lk=,tag:OYYPDlKPuwwamQWrZQD98g==,type:str]
    KOPIA_FILE_LOG_LEVEL: ENC[AES256_GCM,data:a6koHQ==,iv:4kfr7BfBUluUPEwt/xKNbcTa7rIdmKdMvRJ1MUW5gGY=,tag:KGd9mD5GArIh8JK+a7ZSBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZk95WGRYR0lPMEJWZS9i
            Qi9BejQ2d2thdXlsZDQ1Ylc3QU1TeVh2R0VvCjhKY2FDMGw3bVczeDZiU2oxcEFv
            ZnhRV2dvSUVRemFTZzNZbFIvTmV6V1kKLS0tIDdoVmpEM2lHUVlJQTlsZ2QxOWtP
            UksxamRmdWdqVEQzWHlRWFZxZ0U5dFEKcCa5B75/OZUfPOuC9Z51vPLt8V9gDbHH
            m21+sy1pZ85vdNFwKZZqolvvisyk2CF5MVAwzdyw67irCqrA0qwYmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T00:28:07Z"
    mac: ENC[AES256_GCM,data:54gzmNk7Q5nuzPH0czTXqjXNq45uRwfXhkILpKz04pa3k3RR0uTFJy33utd641jZ8X4JGYsi6kM6iOBWEjVksgtK92VR0QY4FSbEqAFyjjTZ+SNUfcN5g6uUZKd3nhZN84RILSsMBIKMEdbvkCkANo9dlS6mub6icrAWId9mmTQ=,iv:r8lXl9iBb5ZzbQLepN5TuwmvENMKb0iE9o+0wgZmiKE=,tag:Aw+4OcsxHh/KG35uVqcAAA==,type:str]
    version: 3.13.3
