apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: forgejo
  path: ./kubernetes/apps/forgejo/app
  dependsOn:
    - name: envoy-gateway-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-backup
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: forgejo
  path: ./kubernetes/apps/forgejo/backup
  dependsOn:
    - name: forgejo
    - name: kopiur
