log:
  level: info
runner:
  capacity: 1
  timeout: 45m
  shutdown_timeout: 10m
  envs:
    DOCKER_HOST: tcp://docker:2375
  labels:
    - oci-build:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:0.1.0@sha256:362b607c8d9ba639c1c0972cde430cf122323763cff691c31d472128e30a82f5
    - runner-rocket:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:0.1.0@sha256:362b607c8d9ba639c1c0972cde430cf122323763cff691c31d472128e30a82f5
cache:
  enabled: false
container:
  docker_host: tcp://docker:2375
  options: --add-host=docker:host-gateway
  privileged: false
  valid_volumes: []
  force_pull: true
