log:
  level: info
runner:
  capacity: 4
  timeout: 45m
  shutdown_timeout: 10m
  envs:
    DOCKER_HOST: tcp://docker:2375
  labels:
    - linux-docker:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:1.3.0@sha256:3bf8dbbd8eb40387f200f6bbb8854cea1cbfab71bfa1046edb3273999ffae67e
    - runner-rocket:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:1.3.0@sha256:3bf8dbbd8eb40387f200f6bbb8854cea1cbfab71bfa1046edb3273999ffae67e
cache:
  enabled: false
container:
  docker_host: tcp://docker:2375
  options: --add-host=docker:host-gateway --dns-option=ndots:1 --dns-search=.
  privileged: false
  valid_volumes: []
  force_pull: true
