apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-registration
type: Opaque
stringData:
    uuid: ENC[AES256_GCM,data:iHG+pOMVbfg/p/StggmIKc2mV4c0g6pCrd9NG+faWW9p5wKU,iv:okUttDMKTxJvwVEuehy1uCx6HjfsQM/xyE3dV+IkiMw=,tag:q4EH3vRNE1O1+jmpUTDXbQ==,type:str]
    token: ENC[AES256_GCM,data:PWaIt0W2kLl9nd9NgVTD2qQqMxYZHgt2by8aSz/JF1JJGtC9anhpXw==,iv:gpuabnxekyFTBqWZwl36OZuqzdLTn06lwKTM4l4xf3A=,tag:LsrXuBZRlZwS0XrO/L46Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVnU5clMvYmhiUTJqMHdH
            MmdqK1QyQ2JpYktZSVR6dWhNTklEVElGenlVCmFDSGdxbktreGVHVHFSVFBNakV4
            YmhxSytwSVI3N1g2QUp1cENhMzlSd00KLS0tIGFPSmhhVFZhVDFVOEU5TktmTUwz
            OU1iWjF3UHhMbktyeENPUkpEb2xCK1UKTW7J5x7djxJciLA5ekq1FRtDdFPqnRkS
            9BWoutAvSIjJnJoYaUfvQ6gV1lvcuNt2EMBynQdSPB9A7EkPVJuA8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T16:24:40Z"
    mac: ENC[AES256_GCM,data:vXd7g2NCo0cTDkRLco7UOMhsT/NDAN7pgUCaCF/F6Z81Rg15JuwbHw98n3ii80AAJhCO1TkhehjW6VNZLrnN1wsJyk6L55Rw9RMX7dLdmEDNYRESCCX0MWWWcqlXoySZfR9UEBoAIK7paHbSJqXxE9+qx0bFqd1o2xOacP5Pji0=,iv:2fYTjNUEkGI78FHL4FLo5KfPDFWZ+a1WdzgLzp6/3JM=,tag:uqBlSwaThwrtIormODRBzg==,type:str]
    version: 3.13.3
