log:
  level: info
runner:
  capacity: 1
  timeout: 45m
  shutdown_timeout: 10m
  envs:
    DOCKER_HOST: tcp://docker:2375
  labels:
    - oci-build:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:0.3.0@sha256:fe6cbc1e84f52d08c41b68d21d5eabcfeed9292c282ff19955a9b4aa7dd05a14
    - runner-kubernetes:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:0.3.0@sha256:fe6cbc1e84f52d08c41b68d21d5eabcfeed9292c282ff19955a9b4aa7dd05a14
cache:
  enabled: false
container:
  docker_host: tcp://docker:2375
  options: --add-host=docker:host-gateway
  privileged: false
  valid_volumes: []
  force_pull: true
