log:
  level: info
runner:
  capacity: 1
  timeout: 45m
  shutdown_timeout: 10m
  envs:
    DOCKER_HOST: tcp://docker:2375
  labels:
    - oci-build:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:0.2.0@sha256:1b5bc2dee2192645d729b1be9a1d6f42a7720972c1a1c2e0d13f3498207f1ed5
    - runner-kubernetes:docker://forgejo.jetersen.dev/jetersen/homelab/runner-job:0.2.0@sha256:1b5bc2dee2192645d729b1be9a1d6f42a7720972c1a1c2e0d13f3498207f1ed5
cache:
  enabled: false
container:
  docker_host: tcp://docker:2375
  options: --add-host=docker:host-gateway --dns-option=ndots:1
  privileged: false
  valid_volumes: []
  force_pull: true
