apiVersion: v1
kind: Secret
metadata:
    name: paperless-kopia
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BiKOAt8KoYAWPXLJ9d4Xyz+GxYzrW0pjiS3KJEnp1zQ=,iv:gb3C3s5H08lalsB7G/zfHpwJHTRKmXk0VwDdXJKnrqo=,tag:Mp/DDKOVzMRdw5shScAgKQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:edE=,iv:8UuR2Y1GnUpzkCm9KhmxGa9W8hNp8rFmjBmnzimZrVw=,tag:lje1J27WAPzrGP+eZAI6nA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+6+NrJs9lL3sEH0NvKAz/XQGb4BKec0/uWlWOE7/SDY=,iv:R6DaeX6VpCZ7tjpfQbUHH3wq480lDXVDc47yxN5Jreg=,tag:ub3uaIsZwJ4Ry3TGpLd3iw==,type:str]
    KOPIA_BUCKET: ENC[AES256_GCM,data:LGgZrPcUbto2dQyKCzNr1LsCIqlwVQ==,iv:vXMdnSLlH5I02TP+mjEDX3Q2YM7AG/EeKSb8mIpvIv4=,tag:AGdTWzg0wNwivirdYMRIFA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:FxvP86yzNAhX48PJp2lKCUmDU/+2RLk6cjpEC74lq9JTvSGpHdNF7WKuz186HAqYR8c3NxP9BSBIqa42hEwlmQ==,iv:RpDsR/dOMtxF7ZKs9lqgeRNct5CLKCxz2hGGuH1bn60=,tag:fWV/N0qRN2VY3tCKEhNMRw==,type:str]
    KOPIA_PREFIX: ENC[AES256_GCM,data:ixlWEfae/+jTR5yKmsKf9zknHCCb,iv:pqgjRUx0LuHspzsPBwyhhsyxBhmjZwFvQOqBdHlP+cE=,tag:aFqKWALLNaZRRHzj10q38w==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:IXfHV3o52ZelZdE2GFtVlMHzK0At/g==,iv:/HcUkMDU9hzP5HujBE2BWPy8Kyi6qJFfFQplbdScdpc=,tag:FIKppqXwKpjw6jOa0lNV6w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWWhUV243c1MxK2ViSXJk
            MGpvZkNxOXBVVDQ2WmZGTnFhRkwyZkFKZTBRClc5WFV6Q3g5eDgyL25sTWVIMUFR
            S2RiZVR0L1BYbFNyYy96QWtqR2RqdGMKLS0tIDdJYzZwL3ZsNFpQNkZCSmNNRnFz
            SmJCalJyZ1RWVU15dVI5SkY1NE5VcmsKOEbyDSH3ztCollFjnrfuorwbXu8yFtYS
            SmNi9BJYpolXiG66TpG4zH2mpBkcz2DMxnWLqq/WMk9t/K2ZyYnaRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T15:21:43Z"
    mac: ENC[AES256_GCM,data:dF+EN3os+UgsliNnIR5yH0LGXVtOmKu6oqkpS+oWob5+twkqh2/QDiXIphCrELsmeNafZD33V4FW4Rizb58y6B2wpSob2liw5n0gN6RAU6/bflnaK1yXuVgPVnhYXIGrrugLJxxbo17r6YapKnqREnSFIcSZmkahea9wwbQTNcM=,iv:WsxYMuQIgtF9N6+FwgQHLtNHdlAyR7Bqrnh2xqBXzFM=,tag:U2ta7a5NRbyKJUxsQ97ipQ==,type:str]
    version: 3.13.3
