apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: forgejo-kopia
    namespace: forgejo
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:d38DDExzuTNi86/A33obxJrUDmQhQeLkuJPFqGYxKN73JFu+cwseGJ1TflJGvlo2ugVzTNo0DTwjO6ystSML6A==,iv:EGOeIXz2kSsO2Q3o1zW8gxNb5JdG4M/UC7ZtEoMprA8=,tag:mhJ+o68GKhw3lcrpcYf8Lw==,type:str]
    KOPIA_BUCKET: ENC[AES256_GCM,data:IelRSlRKRmhohCQa4zXtPXuxhNYa4A==,iv:N/Nd4onkl99VzRzZZnMQJR4bKfN9YYIyf9HUbSz0YzA=,tag:E15L0PsVoPEo5hzVhGJFSA==,type:str]
    KOPIA_PREFIX: ENC[AES256_GCM,data:lFwOcdy6vBWZK+erDjAMHhWx6iOb,iv:V8QCdMZi5Nl1EQGadTXuoHfWcWYyhdbqcEAkq3VPaMc=,tag:3J5kyu1usTCsOdCtiu1Sug==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:8DKL2jUYBkoMaVoZ73/FZjk3sTdNWA==,iv:eb1CNEDZYGzuSf2p0w0XV0CwNPHhuxdO80wmmLEzrJ4=,tag:3KA0fQjp976b9CJsxa/tKA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:Kg8=,iv:lIvCg6nCCX0XNVjfxsTEhaeIS+biU6YbRy1jTjomlLc=,tag:rUk7Qhvom87I5NOfXC4F9Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VfHN0PUG23gM+smi6lLNrRwlVo2SNR4fb4+MbDM6IRk=,iv:GQ5pYZAVdEXEgaCP6cEUq7ixVDuhL37afpv7vsARf2E=,tag:Kvq6X0lwrQ1+X4mkIa5wIw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XVddvhbei3o4YOS4QJy1hyEUfuNDLRDVCv5pVDS+P2Y=,iv:rLRWGFsujV6ZE7AHn6UmfQ45O4vBqP0u0tXXlLFIad0=,tag:dkmBNTVjLT+JCjCFf36RZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV0hVK2RQUXJFakJWVk9W
            ZlhWMTZjNG1lVUN2dE1naDBUSkhGR1RtUDFnClB5L0FwRDdMMExaY1N4QXg5WVJn
            dlVhNXFDcjVYU1NxOXNnbEFUV1JwZVkKLS0tIFFkc2NWS0ZvYlFvTnVWNTNlK1hQ
            eEdpcnlBQ1VISklzdDVBaG5tZjVPc28KMDipPuf36O8OlnG6bVofOEgvK4/daNLg
            J7p0W4JpEKyRe/UlItGgFJ45KUne2mmf3aeECpda8Sv544tgf1k9Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T11:43:33Z"
    mac: ENC[AES256_GCM,data:mmCbwbCbv/PDaUwNLURmpsKCjNlUAcYQm2ghM5rioVExxPXWkSfSUxpo9lxeDVhchJtn1CuvVo1dYHxswGjA+MdCLcqhqK9muqm7obLt3sOXAJ2tPFLkJKztgGJa3YezpCZAamWFY4O8BXDw/ryPgmNO8eYn1c7cwoNH+JOIIZY=,iv:KlCv9TBOH07z0bOlnk4RJsYA1DXY5ls0BD604Y/FGhE=,tag:4VjK5PzEQaV4HHyExyQCLg==,type:str]
    version: 3.13.3
