apiVersion: v1
kind: Secret
metadata:
    name: forgejo-ci-credentials
type: Opaque
stringData:
    runner-uuid: ENC[AES256_GCM,data:GLbssqIIQ8/tM8U7ZiONa/dXGRxecy+O+0MoX/cPiq3Q1K7y,iv:Lzl/TC8lCVFf7k4rRTITBKeXZZXz4uYKmrb+uEEmX5I=,tag:qPiVUZnlaV2Fog7IAC+Oeg==,type:str]
    runner-token: ENC[AES256_GCM,data:044ajuZjzWB49Tb/cSCWyD1xbuE3qZaVh/5vk9t02UKezaR/Zolr+w==,iv:gm3PmHvOeufXbi4/Y6EfWThTmgg2oLVZFvfhtQ/0mww=,tag:J9hnvWqoiHOPKwQ9n7ka+Q==,type:str]
    scaler-token: ENC[AES256_GCM,data:b91J7dJS6OA88sPWZgo7KMWUwQ+PdtnWvSMWvnWXk8AKoNfwngET5w==,iv:CTplzow8G6L++1KKsslhDsufA3cOs/D7bzeLsEBfe0E=,tag:wo7Xq+439BKs5yweVKY18A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYk9GZ2dNV1FGZFRjK2g0
            WWJwR29TTjV4TzBWVEk2d1EzZHJ4ZmFLYXdVCmVBZ3ZHaldnYVRrS3BPbnNtVi9N
            SkJ2c2R2ejNjbmIxWDJmVEp6TzlDcXMKLS0tIC9yZEJybUl0U09YK3d5b3gxZXh6
            dWFkZHR6Z1pJTGxvVVk2Z0o3K3NrRnMKW5h2nF5EufpV9ADzkU6BwHapLDVKVXxp
            nX0t8TWTFea6jkts+ASKq0F7fH2P+wwPQ6+ghrCSOHawqlpaDAPE8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:13:47Z"
    mac: ENC[AES256_GCM,data:a+RaLMbe6Cyp9QIFl42vf5l/NORfZc5xUQjHhiFhsWXNkOvTyvPcI4H7j0+CCP8gi+3L7nAKKbxD/xFR/UDTFWHqIc8CmfEuPxmxku74WcVsgRH/+lPvaYicLM+mWLGIJUrlHB6GsexVJ+WfrGxX7N6ct2PofYpxOlJVwwGzi78=,iv:J3zcnk2gIpXZ7yj2+WYgjdjOwWFRs8P4AIJqokpNEa0=,tag:AI6E9QeAiFirpnqpSSg06Q==,type:str]
    version: 3.13.3
