# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-ci-cache-lvm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: openebs-lvm-thin
  resources:
    requests:
      storage: 20Gi
