---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-technitium
  namespace: external-dns
spec:
  chartRef:
    name: external-dns
    kind: OCIRepository
  values:
    fullnameOverride: external-dns-technitium
    interval: 1440m0s
    managedRecordTypes:
      - A
      - AAAA
    policy: upsert-only
    triggerLoopOnEvent: true
    txtOwnerId: homelab-technitium
    txtPrefix: "_owner_"
    annotationFilter: technitium.alpha.kubernetes.io/private notin (false)
    domainFilters:
      - jetersen.dev
    extraArgs:
      - --annotation-prefix=technitium.alpha.kubernetes.io/
    sources:
      - crd
      - gateway-httproute
      - gateway-grpcroute
      - gateway-tlsroute
      - gateway-tcproute
      - gateway-udproute
      - service
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/bugs5382/external-dns-technitium-webhook
          tag: v0.2.0
        env:
          - name: TECHNITIUM_HOST
            value: http://technitium-app.technitium.svc.cluster.local
          - name: TECHNITIUM_PORT
            value: "5380"
          - name: TECHNITIUM_USER
            valueFrom:
              secretKeyRef:
                name: technitium-auth
                key: username
          - name: TECHNITIUM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: technitium-auth
                key: password
          - name: DOMAIN_FILTER
            value: jetersen.dev
          - name: SERVER_PORT
            value: "8888"
          - name: HEALTH_CHECK_PORT
            value: "8080"
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
