apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:jEdDtnM2I9BnJRLcFf5HoviIwz4TI/+8C1qsjGVo7zY=,iv:1T49uV258vp/Un2SygBrr732VCuU+BU21abc+NixIlg=,tag:MWE3Z4zZF3lPEa9uzGlP5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V0lzR0VFdEVQekw1M01G
            c3VEWWdVd2grdTl6RldhazNJWkpmL3pDUDA4CnJidDFHbVFnRG94S29leDQwYTNW
            cVdtTjZueFNCTVkrNXRCT3BtNHAwbVkKLS0tIGp1TXZVUGNFalZCUkU2OWFyUnhZ
            bVMwTnNWUzdzUlU3QUs1R1pnQlhPNWcKYccb/3nzraJSQoySW/e5Hm6h72oa001W
            g4QPKPkcnptEdydLRr8X4S/3uc/+GfhS9iwoMDCn/8xemKAg7s08jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T23:10:49Z"
    mac: ENC[AES256_GCM,data:7oX7a4NRsIiSb8vbbHdvNnDs/MVlTEsXJinP/2nS1Yo8pukG06mxuFsZn8CM1erZtsk9a3WWGKS0K2IJ9C/FY9VHnsoGgA04A8pFnsPYYp3yVYHdogODWJrEMa080ITGp5T7pi7t8DQGYb8snRrBa/1RufqUMm63RYZmoAmi/zQ=,iv:NJcKMwZ5IMAkiE7WriHAm8kMaldyJ2Ac5iEXvF00Fns=,tag:e8ADA2Ptlef7FrtnVvB8ng==,type:str]
    version: 3.13.2
