apiVersion: v1
kind: Secret
metadata:
    name: photoprism-admin
    namespace: photoprism
type: Opaque
stringData:
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:NP0J1bHBG6NIbrOuTt2MsA==,iv:3JGS6+oz5R0BSOpeoqWKZuZNecLstnYTIlHmv9gmxKw=,tag:z4SiVL4CrVh14HianAzaPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0MxQ3EwM0NZcUE1Ykc0
            U05XWkExT3lNeDd6SUZqNU9idk0wMm5jR0RZClNEQnhNWnp6SXphOEs1Y3hZTnJX
            ZWZaekwwNTZac1BrbWFwc1hVcEZYZjAKLS0tIFpOVDRHd2VLdnVUU2lYVkxOdDA5
            a2hjYm8rUFFtTHhRTjE5ZDdERktielUK1s4Ewxt22Pej7KGwzehjAa72gk+7Cd+N
            ZHu/j6DpnUYY0RlKdSAh5TaGosnRUSkjP7pBLOP9HiK2Swl8maQjcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T17:25:52Z"
    mac: ENC[AES256_GCM,data:bFM+5jaqjsbw9JkXWnQgJzlvRZvce35g+5FXUt0tKEM5SqqwIt/i5CsTFKWtzlf0VTpzK+vCV4IfF847tDahzbjI2rE6xmM82xLg0uJMQxG+QChijcZqVOPCl/Un8DMjBe4oR1x7H/EtDjrNj/dsrBAQeIID8N68BrnMQhDsyeY=,iv:jvngFQcTlgDwxP6lklUQK03Yq2hQTtUH+n1lK7hb9Lo=,tag:0yl6YEdB+qhth1LVCm8OdA==,type:str]
    version: 3.13.3
