apiVersion: v1
kind: Secret
metadata:
    name: towonel-api
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IBxkPOYiVqy0857qyrf7QNVR3zF4EKj8VYm1s58N6oDmZzi5nIvdCH/UzTcDByo=,iv:ZMw+Yi1Z2WSQoEGC/THwsw8ge4KxxBwrtqMd8hZr+SA=,tag:JC1R0anKDbnXWAmQFKU7SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L0JWQ2dXNzczaUtQcDlt
            RWtQSnFiR1ROMjNMaFNMdkkvam91VHJiLzB3CjIxK0dIU2FMNk5ydDBtWlVOVmV1
            akVSalNwWE90cEFCRkRkMGFVVFpuODgKLS0tIEx6WG1vTVFHbHAzSE0zWE13ekor
            cTFCdHVLUnpmRWsrKytkY3MvRFZFQUUKEuhq1N4eLofxW5XZMU5scPnS97BC2NRR
            raWK219EwVQfUS5lbKYrv8agdYxxLdt1r+TfTTNkqsIggFyQ5rQs8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T21:23:31Z"
    mac: ENC[AES256_GCM,data:GwD+qNbvNr4OA6fzDFHLS7GMyh3KeYt5kHbSOwZ2uMD/iDBK/usJy0ga+CsMPMDVj2ZWv2PZMgsQnU/KkPRInBbOjxYjeDUlUr3YS42cg05eo5SjyguHJ42PSg1b8PWmC9kUOq6eI+BucCRvglmo4xjC8AjLERAfhSmhhgGv4zQ=,iv:oQLWH7vQRVQ29mVdB2HjmxtU9s6eKpUhK7OFdxbayYg=,tag:vBkTQ1DH50FqdsenzL1xlw==,type:str]
    version: 3.13.2
