TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:daDWzid9aXDlgJuu0oQkGHh27DD5JrUJZlLYGOmvj9Ga7fRcYnCsqh6TK2Z/ok+riMWC4q661k/GwEZwmA==,iv:mkkt+kq9+XqckuZzolgt0mdXHiyBwQyRnQWE6RKikfw=,tag:rB9IfSwAVTkeMFDwmL5zjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a3gxRzhvUHI2RGpKa29u
            eDViTVptdlhNWnYwUU9HbEwzbzdKOGk4bVNrClBYWmtpckZGQmYxY01SQ0YvanIw
            Znhoem5teUIxeHkyRWJPYkFqcXlGeHcKLS0tIDdkV3FVRFkzY1FuTHg3SnA5UVR6
            clUwcEFVU0pmTEl6dXlzdlVJMHJCZGMK5nMNDcjTO4y5r7iQn/P7Wy8MbXIg1Vd7
            TpwJ+EdLFRqpeIsGGvLVDCOdkh2oZ5cLf0YE76vpV6EjkKOr5hA2vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    lastmodified: "2026-05-16T17:32:42Z"
    mac: ENC[AES256_GCM,data:w5qjVWdpEakX9JIM1zN6Ca8oWntJxvuH1a7/05Dy7uwqE+ZSvqprUNvtXaZv2w7QruYZOW0pW0OfeSDUYuQiV8uJem/A1VZ0EUcB9GS283cDLZz655eikrxHJ9cK/JDNNQsldHGGC2LF6pcTuybHS9JlVehLMoN4Q1ERfTgRNIE=,iv:zWHswn76Y8sE2YyuAy0bwjF2ySFpCGaeC6lT0oY3aMU=,tag:17GIhhiy984gy+ArvlA1Qw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
