---
clusterName: homelab
clusterEndpoint: https://192.168.1.10:6443
# renovate: datasource=github-releases depName=siderolabs/talos
talosVersion: v1.14.2
# renovate: datasource=github-releases depName=kubernetes/kubernetes
kubernetesVersion: v1.36.5
schematicId: '@schematic.yaml'
secretsPath: talsecret.sops.yaml
patchesDir: patches
nodes:
  - host: talos01
    ip: 192.168.1.10
    role: control-plane
