---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-proxy
  annotations:
    towonel.io/gateway-service: kube-system/towonel-public:443
spec:
  gatewayClassName: envoy-proxy
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 192.168.1.20,fde2:b84e:c4cd:1::1000
  listeners:
    - name: mqtt
      protocol: TCP
      port: 1883
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: home-assistant
    - name: mqtt-websocket
      protocol: TCP
      port: 9001
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: home-assistant
    - name: forgejo-ssh
      protocol: TCP
      port: 22
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: forgejo
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: jellyfin-iot
      hostname: jellyfin-iot.jetersen.dev
      protocol: HTTPS
      port: 8443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        certificateRefs:
          - kind: Secret
            name: gateway-production-tls
            namespace: kube-system
    - name: jellyfin-iot-legacy
      hostname: jellyfin-iot.lan.jetersen.dev
      protocol: HTTPS
      port: 8443
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        certificateRefs:
          - kind: Secret
            name: gateway-production-tls
            namespace: kube-system
    # Public routes use a dedicated listener.
    - name: towonel-public
      hostname: webhook.jetersen.dev
      protocol: HTTPS
      port: 8444
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
      tls:
        certificateRefs:
          - kind: Secret
            name: gateway-production-tls
            namespace: kube-system
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: gateway-production-tls
            namespace: kube-system
