---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant/flux-ks.yaml
  - openspeedtest/flux-ks.yaml
  - reflector/flux-ks.yaml
  - reloader/flux-ks.yaml
components:
  - ../components/flux-kustomization-defaults
  - ../components/flux-homelab-source-defaults
  - ../components/flux-wait-defaults
