---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - forgejo/flux-ks.yaml
  - home-assistant/flux-ks.yaml
  - homepage/flux-ks.yaml
  - konflate/flux-ks.yaml
  - media/flux-ks.yaml
  - openspeedtest/flux-ks.yaml
  - photoprism/flux-ks.yaml
  - reflector/flux-ks.yaml
  - reloader/flux-ks.yaml
  - searxng/flux-ks.yaml
components:
  - ../components/flux-kustomization-defaults
  - ../components/flux-homelab-source-defaults
  - ../components/flux-wait-defaults
