---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-metrics-single
  namespace: flux-system
  labels:
    homelab.jetersen.dev/flux-defaults: enabled
    homelab.jetersen.dev/flux-homelab-source: enabled
    homelab.jetersen.dev/flux-wait: disabled
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/cluster/victoria-metrics/app