apiVersion: v1
kind: Secret
metadata:
    name: ntfy-auth
    namespace: monitoring
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:pQvrMYfpdy2DSxQcNOHjK8BhWvJnbxMM80RvdX9e078gAeYGXhXD+3O8zw35N8B4UPgGmVKX1xlF0OKpjXbvHJeffqIjKUyE0bUFXHbjz/ldVvDoM5KxbB7Ml4kIOdrPPya25CmoD+K3CC9zGOpW//6Pp+cDAFRTmjBfa32j5W5Vr5ZgXtWe6OgclQBnYDsxMJxurCy31BJw40mY0DR6AwI7EuavTTKRcKSbN5BByAd4cy7LvkQg2k516FgKEJK/pAXAT4xxSFvvfLwc5txAfU0/eoqv6mw2i9lAl1++FPsxaw==,iv:fnQ0JKM3Y3n3a2Y+VsE7lD6LgyS+3Y0KsFnpNja/sOs=,tag:dhmOriUDMhPmowod+fH6QA==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:IjtBOWdC6pp4qqjCYx/0xEUwTGH+rq0BnoJH1N2iFA7B4ptf0xu6qJ6CE8vDrBKR8ooYU8AP3j6HKWPTa1DU0S6qYa4ptN83QNZrkGTherPHvnVt0V59VI/HAtUAhJ8A1awTDx0CxdlnguOy0OxBgsQ=,iv:uMOczesbaNmmy5tItz4FeYNXIaWXKAF5V3G7T5Wzl54=,tag:OB/fmTYn5X5tIRs2LS1ZKA==,type:str]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:yukwnMz1DWUzQAv3DItjlUi0zDgSy0Ocpawr19N/ro7jEZRCcndhfYEZrWwOeiAnI/7Vu6N5C7OwVWRzXA4ZZuljLp2DQwTqyQ7JI5vj94pSO2vpPbv2Iapvnh0uEPAacqxTLD7FapI7/bDCsIj1xmc=,iv:nCd4XG4MIssEmpgNFDhykyvZ3bHPcIzR6BCs98vrVhU=,tag:malHR0aXIrSBEFeM5gA26g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOFh5c2d4VUZHYUFuWmRG
            eGtkYUtPNkE2aFk5U3lNMXkxNWR5clJNWVFnCnNENEMvZWpYUW41ZUV2RC9pOUtJ
            UGQ4NGVQMHQvRVY2b1UwajZ3a3FUVXcKLS0tIHA2eXo4SDhCMzhTMTN1cVgvSkF2
            MHNtSDRQenU2dkpheEFoWm9UUEtGeGsK1u5zsrptoG570k3leTHg4nNgfWdKg0Dk
            GZTIjNDueI7bdDY3nrUfDWYWOYNn9Q5D23/TImeaPzeYg238i1RBaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:55:34Z"
    mac: ENC[AES256_GCM,data:ausKQnVlpr+iFZyIkLKgtESXdvHbStobBOVgvt63tDXTsn/9hLA5SR1KYxqlp5IE2nVBYRFZE9KRPPJ07Tb0nilP/vG+tc5NOAqCx21A6lNb0DuxuwHEo01922Y9eHDuEnoUHj7X+/dFgcJons2e5NifrjFNgc/s/zA3Wjt2UUg=,iv:QCwvZMv0pOFdA9c7Mh3z+6P9zHDvg5oY4lFDjGt4R2I=,tag:dbMDL4A/fWIlhTy9m7S5+w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: ntfy-alertmanager-auth
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:QoHVbi1V/s65AtQBwko9kAHmiYMg6ZVNi9Ovo6li2Bk=,iv:m7vTORgfruRBknBpkL+qpgzq2jRRcO7tj0/d6mQmVTU=,tag:Y/Jpy0oW+Rf/hap5xKWyqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOFh5c2d4VUZHYUFuWmRG
            eGtkYUtPNkE2aFk5U3lNMXkxNWR5clJNWVFnCnNENEMvZWpYUW41ZUV2RC9pOUtJ
            UGQ4NGVQMHQvRVY2b1UwajZ3a3FUVXcKLS0tIHA2eXo4SDhCMzhTMTN1cVgvSkF2
            MHNtSDRQenU2dkpheEFoWm9UUEtGeGsK1u5zsrptoG570k3leTHg4nNgfWdKg0Dk
            GZTIjNDueI7bdDY3nrUfDWYWOYNn9Q5D23/TImeaPzeYg238i1RBaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:55:34Z"
    mac: ENC[AES256_GCM,data:ausKQnVlpr+iFZyIkLKgtESXdvHbStobBOVgvt63tDXTsn/9hLA5SR1KYxqlp5IE2nVBYRFZE9KRPPJ07Tb0nilP/vG+tc5NOAqCx21A6lNb0DuxuwHEo01922Y9eHDuEnoUHj7X+/dFgcJons2e5NifrjFNgc/s/zA3Wjt2UUg=,iv:QCwvZMv0pOFdA9c7Mh3z+6P9zHDvg5oY4lFDjGt4R2I=,tag:dbMDL4A/fWIlhTy9m7S5+w==,type:str]
    version: 3.13.3
