# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- lvm-storage.yaml
- sonarr-export.yaml
- sonarr-secret.sops.yaml
- sonarr-nas-secret.sops.yaml
- nas-storage.sops.yaml
- kopiur.yaml
