# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-kopia
    namespace: media
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:fVjb9DoplkfvgnA4t4QeQBoNUYS3tm7l0gQY/uhEqk5xMbbTcqISPQ==,iv:2vlPACbIqitgNG7PvB/WTnG7jHbUTEpV6cnU3345Awg=,tag:PKQ1hdQlftcLOuBY+hAptQ==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:Rt08vbmuFVL/sgsZGnQezrPQlPqKEIyVgnURTn+FjgsdPvYKg7uQhNfSz+t28IS9JQWUdPojiUgOMCYhLVNXOw==,iv:hT7Gv4ewybiJWxP+sf+mmb5Y7MD15+xeyXpu7nSQnKQ=,tag:fyL29gEhD3TYahgytJC1Jg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:K+4ZpwUw+sgWvyTAezsAWUlYh5bb0Xw8uvXExZOlioI=,iv:iEoznWyGuvRI1PTFbvI6ikWUx87c4iFnHqmfEtxYgiM=,tag:cVFfnUpabZKWf0T6yXp56Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:egIpZvNoPfMXeNdVlwhAPrCHz+bKkFh+oYiWhg3gXyE=,iv:2o6TKfEQQ4kOFHHkuV2aKpEewCtupDX6Axmz8ObcZrw=,tag:JKDwfNSqUoxG5LGZ0tOhRQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:f6A=,iv:WyN2jB/jICf5S+RIK+/sr0MvTddhB8brdFtFxV7mAX8=,tag:StW2rlpGM3FAh5sN07h/Aw==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:r2tV9+27ghxpjiVEV2Ib3v/vS4CtWA==,iv:lHBZiVJCADHBS3l36/HM/ylzM0tyC0UhMG7FGJGIIEI=,tag:EnnhkD91GKtCysNsd5qp2g==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:6CnVs0s=,iv:6LVPU/YgECyNlI/Q6sYOWEipRFCt4CuLHmqwz7JCuGY=,tag:WQpycMhNkYmrtpsVBK9wRg==,type:str]
    KOPIA_FILE_LOG_LEVEL: ENC[AES256_GCM,data:Qaj/JQ==,iv:d/p/x214m0EMjrUCbiVgg+tdUJ8x/1loxIjHTW0e904=,tag:tTK8W2LC06wNh3z/giQGPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOGc4RVNGQjRBTXFpSU9r
            VUQzbUFtWGpHcEw5V3NQb3RNZW8wYkxUSEdvCktoWmUxSFU3WktUY3hxOGM2Z1FM
            MytQZTVLSGtpdTFwanN0VTF3d3B6blUKLS0tIFdmdmg0Mmk0OWYxWlJqM1hYcjEy
            YVEyYnUyU044WFM0ekRBc2Q4RC9icnMKDRTC5+jXcK1LSrKocyql9d0Zg1FwsGw2
            lA2PFi0Qu3n0syHxrE2tAYUc1zRKWECENr3W5moGVK9qvruJAMJGiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T02:29:54Z"
    mac: ENC[AES256_GCM,data:Y+UzH8BRGYR4hMuS9gygS4njFv2khkyEaIVRibK6pQyjnPrgD9dgfY0U/7kU/A4mrSR3RLln7p15sBS+36vg4P5ssyCR22s8oFJl0WbXBjyAWpJ6tjPyrQ5j+i5I9WELNDbl9o7G79K7fouV2YyDLL4eHvItIAyJ5pPfmq+kzxA=,iv:pbpR7JDiTAsIzDafo4c4k0abfu2AWmuTN8ztq8y0ZKw=,tag:QVE1/woirOIGpTVMFh9c5Q==,type:str]
    version: 3.13.3
