apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
spec:
  paused: false
  sourcePVC: sonarr-backup-exports
  trigger:
    manual: pilot-1
  kopia:
    repository: sonarr-kopia
    copyMethod: Direct
    cacheCapacity: 1Gi
    username: sonarr
    hostname: homelab
    policyConfig:
      configMapName: sonarr-backup-policy
    actions:
      beforeSnapshot: bash /kopia-config/check-source.sh
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    moverResources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 1Gi
    retain:
      hourly: 0
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
      latest: 3
