apiVersion: v1
kind: Secret
metadata:
    name: sonarr-kopia-nas
    namespace: media
type: Opaque
stringData:
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:SZ+93MhPbX82IeO1kQscvAmZKlciWQVVD6Sri9wkXEw=,iv:JiU47wRLLr+Orqo1uKIfqn9e3ocXbem0DARxYfaG5yQ=,tag:n/yQz1dytHi/jk0Z0vF6wA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:cqITtWT82DcCJbFdP6+i4kgAYN7V6FdVv0LG6rApSP2ek21Yb2qApyu0VNnU3oCg6Fby4JhSglYIOqr0c9jVSg==,iv:Foxni4O4d99yda6pTaowUqqO34F1BECR4+R3mhbzwlM=,tag:7VDA2HCBYP3f0UTTx/LZ5g==,type:str]
    KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:DWWvx90=,iv:+zHuzFdt6mIlFzf8LQ9oIAQW5Wu0gjYrYTqApObNdmQ=,tag:qDsLNRpb3LWSYZ12pXv/BQ==,type:str]
    KOPIA_FILE_LOG_LEVEL: ENC[AES256_GCM,data:omjOnA==,iv:0EwEiUHlLhMD9l0bVoSF5sqyil382vq6uj6tcFhc2+Q=,tag:cFn+il9vaqtDLRkBkQs9xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXUxQ2V3RkpCZS9rWjRS
            c1l0bldRSVNJVHJiY3NGU2hsUm9NQy9OTmdvCmprREJJSTBsR2ZiazhzVFFuZmx1
            b04wZ3NLSW9HK0hJSm95S1UzeE5wSzAKLS0tIFBuSEpmcExkNWRYUUhXenYxeGI1
            M0Q2THZCNVFlU2lZYUVqMWk1dzB4b00KJaSu0ToDwQ4Xhq6NrO4FDNU1f910+hXM
            p+4aum73rZa0yblLDgBliymWGxaSExVFA4loHEI5lUz4gHftVKy51g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u0m8ryqg7hfhuykraxe35v4xzw92a03w9jpt75yv3m57g6pvpp0sf24mdy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T03:58:42Z"
    mac: ENC[AES256_GCM,data:6BCN0g1wiyEWNmq3U+vQmNW9HGiefSLBdXterYKAA3d7gQAkdndtYuSddILptPIC18aUhNqyzRMmlzsL3772hwt63kyibX8d6lCL5Dgl8X6ADOuZgn5P5tbR9ruITDcTrZx7XmaqsqopmPdHzl7H0RQ5WCTs10SiFpZWLsRae6I=,iv:xQseVQ0nfXBmc4sI6I1518/xWRxIjcwmU5wrZ1jitlg=,tag:dDPO2AoWsZw18FPDleuAcA==,type:str]
    version: 3.13.3
