# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Publish Flux OCI
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
concurrency:
  group: publish-oci
  cancel-in-progress: false
jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-26.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: fluxcd/flux2/action@b9c17924adb533d3617ec7de97a7b0f4acc07b39 # v2.9.6
        with:
          version: 2.9.5
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.ci/actions/publish-oci
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
